version: '3.4'

services:
  productdb:
    container_name: productdb
    restart: always
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: ProductDb
    volumes:
         - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    environment:
        - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
        - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
        - "5050:80"
    volumes:
        - pgadmin_data:/root/.pgadmin

  portainer:
    container_name: portainer
    restart: always
    ports:
        - "9000:9000"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data

  productmicroservice.api:
    container_name: product.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=productdb;Port=5432;Database=ProductDb;User Id=postgres;Password=postgres;"
    depends_on:
      - productdb
    ports:
      - "8002:8080"