version: '3.4'

services:
  productdb:
    container_name: productdb
    restart: always
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: ProductDb
    volumes:
         - postgres-data:/var/lib/postgresql/data

  categorydb:
    container_name: categorydb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
        - "5051:80"
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: password
        ME_CONFIG_MONGODB_URL: mongodb://categorydb:27017/admin
    depends_on:
        - categorydb

  pgadmin:
    container_name: pgadmin
    environment:
        - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
        - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
        - "5050:80"
    volumes:
        - pgadmin_data:/root/.pgadmin

  portainer:
    container_name: portainer
    restart: always
    ports:
        - "9000:9000"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data

  productmicroservice.api:
    container_name: product.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=productdb;Port=5432;Database=ProductDb;User Id=postgres;Password=postgres;"
    depends_on:
      - productdb
    ports:
      - "8002:8080"
  category.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://categorydb:27017"
    ports:
      - "8080"

