version: '3.4'

services:
  productdb:
    container_name: productdb
    environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin1234
        - POSTGRES_DB=ProductDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data/ 

  pgadmin:
    container_name: pgadmin
    environment:
        - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
        - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
        - pgadmin_data:/root/.pgadmin

  product.api:
    container_name: productapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=172.22.0.3;Port=5432;Database=ProductDb;User Id=admin;Password=admin1234;"
    ports:
      - "8080"
