version: '3.4'

services:
  productdb:
    image: postgres
  
  categorydb:
    image: mongo
  
  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  mongoexpress:
    image: mongo-express

  productmicroservice.api:
    image: ${DOCKER_REGISTRY-}productmicroserviceapi
    build:
      context: .
      dockerfile: ProductMicroService/Presentation/ProductMicroservice.API/Dockerfile

  category.api:
    image: ${DOCKER_REGISTRY-}categoryapi
    build:
      context: .
      dockerfile: CategoryMicroservice/Category.API/Dockerfile

volumes:
  postgres-data:
  pgadmin_data:
  portainer_data:
  mongo_data:
