version: '3.4'

services:
  productdb:
    image: postgres
  
  pgadmin:
    image: dpage/pgadmin4

  productmicroservice.api:
    image: ${DOCKER_REGISTRY-}productmicroserviceapi
    build:
      context: .
      dockerfile: ProductMicroService/Presentation/ProductMicroservice.API/Dockerfile

  portainer:
    image: portainer/portainer-ce

volumes:
  postgres-data:
  pgadmin_data:
  portainer_data: